---
title: "data_viz"
author: "Caleb Neale"
date: "4/28/2021"
output: pdf_document
---
# Read Data
```{r}
load(file="data\\cleanedData.Rdata")
```


# Equipment Plotting
## Autoplot variables of interest
```{r}
library(ggplot2)
library(tidyverse)
library(lubridate)
library(fpp3)

hist(equip$totalHeat)

autoplot(totalEnergy, .vars=totalHeat.AHU, ylab="Total AHU Heat, kW")
autoplot(totalEnergy, .vars=totalHeat.room, ylab="Total Room Heat, kW")
autoplot(totalEnergy, .vars=fanEnergy, ylab="Fan Energy, kW")
autoplot(totalEnergy, .vars = totalHeat, ylab="Combined room and AHU Heat, kW")
autoplot(totalEnergy, .vars = totalEnergy, ylab="Fan, Room, and AHU Energy, kW") 
```
## Area Plot Total Energy
```{r}
# get longform data for plotting
totalEnergy %>% select(-totalHeat, -totalEnergy) %>% filter(equipment == "AHU2E") %>% pivot_longer(cols = c(totalHeat.AHU, fanEnergy, totalHeat.room), names_to = "datapoint", values_to = "value") -> longAHU2E

totalEnergy %>% select(-totalHeat, -totalEnergy) %>% filter(equipment == "AHU2W") %>% pivot_longer(cols = c(totalHeat.AHU, fanEnergy, totalHeat.room), names_to = "datapoint", values_to = "value") -> longAHU2W

# stacked area plots
ggplot(data = longAHU2W, aes(x=time, y=value, fill=datapoint)) + geom_area()
ggplot(data = longAHU2E, aes(x=time, y=value, fill=datapoint)) + geom_area()

# proportional stacked area plots
ggplot(longAHU2W, aes(x=time, y=value, fill=datapoint)) + 
    geom_area(position = "fill") + scale_fill_brewer(palette = "Blues")

ggplot(longAHU2E, aes(x=time, y=value, fill=datapoint)) + 
    geom_area(position = "fill") + scale_fill_brewer(palette = "Blues")
```
## Energy and Temperature
```{r}
weather_merge = weather

# shift weather data by a minute to allow for merging
weather_merge$obsTimeLocal = weather_merge$obsTimeLocal + 60

# merge data
left_join(totalEnergy, weather_merge, by=c("time" = "obsTimeLocal")) %>% filter(!is.na(totalEnergy))-> weather_energy

# plot, filtering out low energy values for when HVAC system is "off"
ggplot(data = weather_energy %>% filter(totalEnergy > 50), aes(x=tempAvg, y=totalEnergy)) + geom_point() + geom_smooth()
```

## Seasonal plots
```{r}
totalEnergy = fill_gaps(totalEnergy)
gg_season(totalEnergy, totalEnergy, period = "week")
gg_season(totalEnergy, totalEnergy, period = "day")
gg_season(totalEnergy, totalEnergy, period = "month")
gg_season(totalEnergy, totalEnergy, period = "year")
gg_season(totalEnergy, totalEnergy, period = "hour")



gg_subseries(fill_gaps(equip), totalHeat, period = "day")

gg_season(fill_gaps(equip), fanEnergy)
gg_season(fill_gaps(equip), fanEnergy, period = "day")
gg_subseries(fill_gaps(equip), fanEnergy, period = "day")

```

# Seasonal Subseries Plots
```{r}
gg_subseries(totalEnergy, totalEnergy, period="day")

```

# Lag Plots
```{r}
totalEnergy %>% select(totalEnergy) %>% filter(equipment == "AHU2E") %>% gg_lag(y=totalEnergy, geom = "point")
totalEnergy %>% select(totalEnergy) %>% filter(equipment == "AHU2W") %>% gg_lag(y=totalEnergy, geom = "point")

```
# Autocorrelation Plots
```{r}

# ACFs
totalEnergy %>% filter(equipment == "AHU2E") %>% ACF(totalEnergy) %>% autoplot()
totalEnergy %>% filter(equipment == "AHU2W") %>% ACF(totalEnergy) %>% autoplot()

totalEnergy %>% filter(equipment == "AHU2E") %>% ACF(fanEnergy) %>% autoplot()
totalEnergy %>% filter(equipment == "AHU2W") %>% ACF(fanEnergy) %>% autoplot()

totalEnergy %>% filter(equipment == "AHU2E") %>% ACF(totalHeat.AHU) %>% autoplot()
totalEnergy %>% filter(equipment == "AHU2W") %>% ACF(totalHeat.AHU) %>% autoplot()

totalEnergy %>% filter(equipment == "AHU2E") %>% ACF(totalHeat.room) %>% autoplot()
totalEnergy %>% filter(equipment == "AHU2W") %>% ACF(totalHeat.room) %>% autoplot()

# PACFs
totalEnergy %>% filter(equipment == "AHU2E") %>% PACF(totalEnergy) %>% autoplot()
totalEnergy %>% filter(equipment == "AHU2W") %>% PACF(totalEnergy) %>% autoplot()

totalEnergy %>% filter(equipment == "AHU2E") %>% PACF(fanEnergy) %>% autoplot()
totalEnergy %>% filter(equipment == "AHU2W") %>% PACF(fanEnergy) %>% autoplot()

totalEnergy %>% filter(equipment == "AHU2E") %>% PACF(totalHeat.AHU) %>% autoplot()
totalEnergy %>% filter(equipment == "AHU2W") %>% PACF(totalHeat.AHU) %>% autoplot()

totalEnergy %>% filter(equipment == "AHU2E") %>% PACF(totalHeat.room) %>% autoplot()
totalEnergy %>% filter(equipment == "AHU2W") %>% PACF(totalHeat.room) %>% autoplot()
```
# Moving average plots
```{r}
totalEnergyMA <- totalEnergy %>% mutate(
    `200MA` = slider::slide_dbl(totalEnergy, mean,
                .before =100, .after = 100, .complete = TRUE)
  )

totalEnergyMA %>% filter(equipment == "AHU2E") %>%
  autoplot(totalEnergy, color = "gray") +
  geom_line(aes(y = `200MA`), color = "#D55E00") +
  labs(y = "Total Energy",
       title = "Total Energy over Time, AHU2E") +
  guides(colour = guide_legend(title = "series"))

totalEnergyMA %>% filter(equipment == "AHU2W") %>%
  autoplot(totalEnergy, color = "gray") +
  geom_line(aes(y = `200MA`), color = "#D55E00") +
  labs(y = "Total Energy",
       title = "Total Energy over Time, AHU2W") +
  guides(colour = guide_legend(title = "series"))



```
# Differencing
```{r}
totalEnergy %>% filter(equipment == "AHU2E") %>% gg_tsdisplay(difference(totalEnergy), plot_type = "partial")
totalEnergy %>% filter(equipment == "AHU2W") %>% gg_tsdisplay(difference(totalEnergy), plot_type = "partial")

```

# Model search
```{r}
models <- totalEnergy %>% 
  filter(equipment == "AHU2E") %>% 
  model(stepwise = ARIMA(totalEnergy),
        search = ARIMA(totalEnergy, stepwise = FALSE),
        arima0132 = ARIMA(totalEnergy ~ pdq(0,1,0:32, q_init=32), order_constraint = p + q + P + Q <= 35),
        arima3610 = ARIMA(totalEnergy ~ pdq(0:36,1,0, p_init=36), order_constraint = p + q + P + Q <= 38))


glance(models) %>% arrange(AICc) %>% select(.model:BIC)

models %>% select(search) %>% gg_tsresiduals()

# from book, what are lag and dof parameters? are these values appropriate here?
augment(models) %>%
  filter(.model=='search') %>%
  features(.innov, ljung_box, lag = 10, dof = 3)

# results of above suggest residuals are not white noise, what do I do about this? no next steps listed in the book
```
# Hierarchical approach

## Plotting and formatting
```{r}
# subset and rename energy data

hierEnergy <- totalEnergy %>% 
  select(totalHeat.room, fanEnergy, totalHeat.AHU) %>% 
  pivot_longer(names_to = "datapoint", 
               values_to = "value",
               cols = c(totalHeat.room, fanEnergy, totalHeat.AHU)) %>%
  mutate(datapoint = recode(datapoint,
                            `totalHeat.room` = "roomHeat",
                            `totalHeat.AHU` = "AHUHeat",
                            `fanEnergy` = "fanEnergy")
  ) 

as_tsibble(hierEnergy, key = c(datapoint, equipment), index = time) -> temp
                      
# create hierarchical tsibble
hierEnergy %>% aggregate_key(equipment / datapoint, value = sum(value)) -> hierEnergy

# plot hierarchical data
hierEnergy %>%
  autoplot(value) +
  labs(y = "Energy (kW)",
       title = "Energy Consumption, AHU and Components") +
  facet_wrap(vars(datapoint, equipment), scales = "free_y", ncol = 3)

hierEnergy %>%
  autoplot(value) +
  labs(y = "Energy (kW)",
       title = "Energy Consumption, AHU and Components") +
  facet_wrap(vars(equipment), scales = "free_y", ncol = 3)


hierEnergy %>%
  filter(is_aggregated(datapoint)) %>%
  autoplot(value) +
  labs(y = "Energy (kW)",
       title = "Energy Consumption, AHU and Components") +
  facet_wrap(vars(equipment), scales = "free_y", ncol = 3) +
  theme(legend.position = "none")

```
```{r}
# ARIMA
fit <- hierEnergy %>% 
  filter_index(~ "2021-03") %>%
  model(base = ARIMA(value)) %>%
  reconcile(
    bu = bottom_up(base),
    ols = min_trace(base, method = "ols"),
    mint = min_trace(base, method = "mint_shrink"),
  )

fc <- fit %>% forecast(h = "1 month")

fc %>%
  filter(is_aggregated(datapoint)) %>%
  filter_index("2021-04" ~.) %>%
  autoplot(
    hierEnergy %>%
  filter_index("2021-04" ~.),
    level = NULL
  ) +
  labs(y = "Trips ('000)") +
  facet_wrap(vars(equipment), scales = "free_y")

# ETS
fit <- hierEnergy %>% fill_gaps() %>% fill(value, .direction = "downup") %>%
  filter_index(~ "2021-03") %>%
  model(base = ETS(value)) %>%
  reconcile(
    bu = bottom_up(base),
    ols = min_trace(base, method = "ols"),
    mint = min_trace(base, method = "mint_shrink"),
  )

fc <- fit %>% forecast(h = "1 month")

fc %>%
  filter(is_aggregated(datapoint)) %>%
  filter_index("2021-04" ~.) %>%
  autoplot(
    hierEnergy %>%
  filter_index("2021-04" ~.),
    level = NULL
  ) +
  labs(y = "Trips ('000)") +
  facet_wrap(vars(equipment), scales = "free_y")
```
# Regression with ARIMA errors
```{r}

```

