---
title: "Project Proposal (Draft)"
author: "Caleb Neale"
date: "Spring 2021"
output:
  pdf_document: default
  html_notebook: default
subtitle: Optimizing HVAC Operation for Occupant Comfort and Energy Savings
editor_options: 
  chunk_output_type: inline
---
# Abstract

# Introduction
In UVA's LinkLab, as a part of the Living Link Lab Program, there is a significant amount of environmental, occupancy data, and HVAC system operational data available for analysis. This presents an opportunity for a detailed case study of the performance of an HVAC system among multiple metrics outside of just temperature and humidity with the intention of improving HVAC control systems' ability to maintain occupant comfort with reduced energy consumption. Investigation of multiple metrics of occupant comfort, whether a given room even has occupants which require comfort, various metrics of system operation, and energy consumption consumption (actual and calculated) has the potential to produce a environmental model which may aid in the development of an improved policy for the HVAC system control problem. 

Considering HVAC usage accounts for 30% of total commercial building energy consumption (US Dept. of Energy Commissioned Report on Energy Savings Potential and RD&D Opportunities for Commercial Building HVAC Systems, 2017), there is significant environmental and economic incentive to reducing the energy load of HVAC systems both for regulators and commercial operators. This same commissioned report cites "Technology Enhancements for Current Systems" as one of four groups of high priority technology options, with  "Advanced HVAC Sensors" as the top ranked technology within this category at an estimated Technical Energy Savings Potential (Quadrillion BTU/yr.) of 0.63, lending particular credence to the idea that advanced sensing combined with more efficient control could be a significant contributor to reduced HVAC system burden on energy resources.

This project will investigate the first phase of determining if it possible to create a more efficient control policy for HVAC systems by developing a model of energy consumption calculated from system operation metrics, validating this model with a limited amount of actual collected energy usage data, and attempting to forecast energy demand with this data.

# The data and the data-generating process
The data which will be analyzed consists of data exported from an internal UVA server which hosts all HVAC system data related to Olsson Hall and the Link Lab, the unit of measure for this project. Additionally, local weather data on humidity and atmospheric pressure necessary for  calculations, and local temperature data, a potential predictor of consumption, will also be obtained. 

## Data
Index:
Time, hourly

Key:
VAV box, HVAC Unit

Values:
- Output Air Temperature (deg C)
- Input Air Temperature  (deg C)
- Air Supply Flow (CFM)
- Air Supply Flow Set point (CFM)
- Local Temperature (deg C)
- Local Humidity (%RH)
- Local Air Pressure (kPA)
- Enthalpy change (calculated, BTU)
- Fan Energy Consumption (Calculated, BTU)
- Total Energy Consumption (Calculated, BTU)

Insert preview and graphs here

## Data Generating Process

### System Description and Terminology
The HVAC system under consideration is a VAV (variable air volume) system which consists of two air handling units (AHU) and VAV boxes. VAV systems manage the temperature of the different rooms in the building by providing specific volumes of air to each room using equipment known as VAV boxes. At the VAV box, air may be reheated to provide the room with the correct temperature of air needed to maintain the environment at the given setpoint. Our simplified model of the AHU consists of hot and cold water coils for heating/cooling, a return air fan, and a supply air fan. Each VAV box consists of a vent regulating air volume and a heating coil. 

### Definitions of Air Types
Return air is defined as air which is being returned from the conditioned environment. In this system, return air is mixed with outdoor air to produce mixed air. Mixed air serves as the input to the conditioning system at the AHU level. Once the air is treated (heating/cooling, humidity removal) by the AHU, it is output as supply air. This supply air is then provided to each VAV box for additional heating as needed, producing final supply air. As this lack of distinction between these two versions of "supply air" may be confusing, this analysis will adopt the terms "input air" and "output air" when discussing both the VAV and AHU treatment processes.

### Air Supply Flow
Air supply flow is measured at the VAV box level and aggregated to determine AHU air volumes.

### Enthalpy Change
As treatment can occur at both the AHU and VAV box, enthaply change (change in energy due to heating/cooling and humidity removal) must be calculated at both stages and then aggregated to find total enthalpy change at a given time. 

### Weather Data
Weather data was collected from **Need source for this data** using an API and then merged into the data using the times. The location of this weather data is **TBD** and was used to estimate local temperature, pressure, and relative humidity. **Check units**


# Formal model of data-generating process - PRELIMINARY

# Discussion of the statistical model

# Plan for data analysis

# References

# Data and Plan for Analysis

The primary goal of this analysis is to generate an effective model of how HVAC system operation affects energy consumption over time, and attempting to create a forcast sing this model.

##  HVAC System Operation and Energy Consumption

### Heating and Cooling

### Fans

The first portion of the project, focused on HVAC operation and energy consumption, requires the collection and organization of data related to HVAC system operation for each air handling unit, including:

- Temperature data (deg F):
 - Return Air
 - Supply Air

- Humidity:
  - Return Air (% rel. humidity)

- Heating/Cooling:
  - Pre-Heat Valve (% Open)
  - Chilled Water Valve (% Open)

- Energy Consumption (Calculated from above if not available)

- Supply Air Volume (ft^3/min)

- Air Handling Unit SEER

### Calculation of energy consumption using SEER ratio

The below methodology is pending verification from UVA facilities experts.

SEER = BTU/Watt-Hours = total change in heat energy in conditioned space divided by energy consumed to condition space


#### Calculating BTU/hr for heating operation\
BTU/hr = C * del(T) * M\

Where:

- C is the specific heat of air (approx. 1 kJ/Kg*K)
- del(T) is the change in temperature
- M is the mass of air = rho*V, using an approximate density of 1.2 Kg/m^3
- Given our data an adjustment will also have to be made to convert from cubic feet per **minute** to BTU per **hour**.


#### Calculating BTU/hr for cooling operation\
An additional term can be included in calculating BTU related to the removal of humidity:\

BTU/hr = C * del(T) * M + (0.68 * CFM * del(w_gr))

Where:

- CFM = airflow in cubic feet per minute
- del(w_gr) = change in humidity ratio in grains

Data is not currently available on humidity removal, so the heating methodology will be applied as an estimated of energy consumption under cooling operation. 


## HVAC System Operation and Collected Metrics of Comfort

The second portion of the project, focused on HVAC operation and comfort, requires the collection and organization of data related to HVAC system operation for each air handling unit and room status indicators for all rooms serviced by an air handling unit including:

1. Detailed data on HVAC system operation
2. Data on CO2, temperature, humidity, occupancy, and other selected metrics 

This analysis will be set aside for now, pending later investigation.

## Improving HVAC System Control Policy

Once both phases of analysis are complete and system dynamics are adequately understood, simulation can be used to develop an optimized control mechanism to minimize energy usage while maintaining occupant safety.


# Exploratory Data Analysis


# Data and Data Generating Process


# Links to sources
- US DOE Report: https://www.energy.gov/sites/prod/files/2017/12/f46/bto-DOE-Comm-HVAC-Report-12-21-17.pdf - BTU formulae: 
  - https://www.advantageengineering.com/fyi/288/pdf/advantageIndustrialFormulas.pdf
  - https://www.engineeringtoolbox.com/cooling-heating-equations-d_747.html
  - https://www.energyvanguard.com/blog/converting-heating-and-cooling-loads-air-flow-physics
- SEER:
  - https://www.sciencedirect.com/topics/engineering/seasonal-energy-efficiency-ratio#:~:text=The%20SEER%20rating%20is%20calculated,efficient%20the%20air%20conditioner%20is. 
  https://www.ahrinet.org/App_Content/ahri/files/standards%20pdfs/ANSI%20standards%20pdfs/ANSI.AHRI%20Standard%20210.240%20with%20Addenda%201%20and%202.pdf
- Supply Air Temperature: https://www.sciencedirect.com/topics/engineering/supply-air-temperature
- General readings:
  - https://onlinelibrary.wiley.com/doi/full/10.1111/ina.12496?casa_token=WXZVCDnNN9AAAAAA%3A-yxXhqtRRzBjY5bNRnOfwfIpDrbxLWxvaFWFe9TMt17Pbim5uxgKQn4R8EqDvDDaE3mU4svSIxvo9GP2
  - https://www.sciencedirect.com/science/article/pii/S1474667016440887
  - https://www.sciencedirect.com/science/article/pii/S1364032113004322?casa_token=UDbPZbtcuZwAAAAA:aR-hPKZ_P-eEZdsk3nO_pjKVmUum4RKqjDi43Jp4-mTD9MqAc5BhJFo7XG4b2qwNo0FLwpfvmWE



