---
title: "Project Proposal (Draft)"
author: "Caleb Neale"
date: "Spring 2021"
output:
  pdf_document: default
  html_notebook: default
subtitle: Optimizing HVAC Operation for Occupant Comfort and Energy Savings
editor_options: 
  chunk_output_type: inline
---
# Abstract

# Introduction
In UVA's LinkLab, as a part of the Living Link Lab Program, there is a significant amount of environmental, occupancy data, and HVAC system operational data available for analysis. This presents an opportunity for a detailed case study of the performance of an HVAC system among multiple metrics outside of just temperature and humidity with the intention of improving HVAC control systems' ability to maintain occupant comfort with reduced energy consumption. Investigation of multiple metrics of occupant comfort, whether a given room even has occupants which require comfort, various metrics of system operation, and energy consumption consumption (actual and calculated) has the potential to produce a environmental model which may aid in the development of an improved policy for the HVAC system control problem. 

Considering HVAC usage accounts for 30% of total commercial building energy consumption (US Dept. of Energy Commissioned Report on Energy Savings Potential and RD&D Opportunities for Commercial Building HVAC Systems, 2017), there is significant environmental and economic incentive to reducing the energy load of HVAC systems both for regulators and commercial operators. This same commissioned report cites "Technology Enhancements for Current Systems" as one of four groups of high priority technology options, with  "Advanced HVAC Sensors" as the top ranked technology within this category at an estimated Technical Energy Savings Potential (Quadrillion BTU/yr.) of 0.63, lending particular credence to the idea that advanced sensing combined with more efficient control could be a significant contributor to reduced HVAC system burden on energy resources.

This project will investigate the first phase of determining if it possible to create a more efficient control policy for HVAC systems by developing a model of energy consumption calculated from system operation metrics, validating this model with a limited amount of actual collected energy usage data, and attempting to forecast energy demand with this data.

# The data and the data-generating process
The data which will be analyzed consists of data exported from an internal UVA server which hosts all HVAC system data related to Olsson Hall and the Link Lab, the unit of measure for this project. Additionally, local weather data on humidity and atmospheric pressure necessary for  calculations, and local temperature data, a potential predictor of consumption, will also be obtained. 

## Data
Index:
Time (hourly)

Key:
VAV box, HVAC Unit

Values:
- Output Air Temperature (deg C)
- Input Air Temperature  (deg C)
- Air Supply Flow (CFM)
- Air Supply Flow Set point (CFM)
- Local Temperature (deg C)
- Local Humidity (%RH)
- Local Air Pressure (kPA)
- Enthalpy change (calculated, BTU)
- Fan Energy Consumption (Calculated, BTU)
- Total Energy Consumption (Calculated, BTU)

Insert preview and graphs here

## Data Generating Process

### System Description and Terminology
The HVAC system under consideration is a VAV (variable air volume) system which consists of two air handling units (AHU) and VAV boxes. VAV systems manage the temperature of the different rooms in the building by providing specific volumes of air to each room using equipment known as VAV boxes. At the VAV box, air may be reheated to provide the room with the correct temperature of air needed to maintain the environment at the given setpoint. Our simplified model of the AHU consists of hot and cold water coils for heating/cooling, a return air fan, and a supply air fan. Each VAV box consists of a vent regulating air volume and a heating coil. 

### Definitions of Air Types
Return air is defined as air which is being returned from the conditioned environment. In this system, return air is mixed with outdoor air to produce mixed air. Mixed air serves as the input to the conditioning system at the AHU level. Once the air is treated (heating/cooling, humidity removal) by the AHU, it is output as supply air. This supply air is then provided to each VAV box for additional heating as needed, producing final supply air. As this lack of distinction between these two versions of "supply air" may be confusing, this analysis will adopt the terms "input air" and "output air" when discussing both the VAV and AHU treatment processes.

### Air Supply Flow
Air supply flow is measured at the VAV box level and aggregated to determine AHU air volumes.

### Enthalpy Change
As treatment can occur at both the AHU and VAV box, enthaply change (change in energy due to heating/cooling and humidity removal) must be calculated at both stages and then aggregated to find total enthalpy change at a given time. 

### Weather Data
Weather data was collected from **Need source for this data** using an API and then merged into the data using the times. The location of this weather data is **TBD** and was used to estimate local temperature, pressure, and relative humidity. **Check units**

# Plan for Analysis
The primary goal of this analysis is to generate an effective model of how HVAC system operation affects energy consumption over time, which can be divided into three parts:

- Calculate estimated HVAC energy consumption using historical data on operational metrics
- Validate estimated energy consumption with historical, building-wide energy consumption data; update parameters and assumptions as necessary
- Create a statistical model of energy consumption in the HVAC system and generate a forecast with this model


##  Calculate Energy Usage from HVAC Operational Metrics
The primary usages of energy in this HVAC system come from treatment at the AHU, treatment at the VAV box, and fan operation in the AHU. Calculations for treatment at the AHU and VAV box level leverage the same equations, and fan equations can be leveraged to estimate fan energy usage.

### Air Treatment
The change in energy due to air treatment (at either AHU or VAV) can be divided into latent and sensible heat. Changes in latent heat arise from humidity added or removed from the air whereas sensible heat is affected by changes in air temperature. Enthalpy change accounts for both latent and sensible heat as is calculated using **fix with Zotero** (https://rdrr.io/github/chrras/climateeng/man/). Equation 1, below, can then be used to determine total heat by combining calculated enthalpy change with collected data on air volume flow.

#### Equation 1, Latent and Sensible Heat
**Zotero source**
h_t = ρ\*q\*dh

where:

h_t = total heat (kW)\
q = air volume flow (m3/s)\
ρ = density of air (1.202 kg/m3)\
dh = enthalpy difference (kJ/kg)


### Fans
Power used by a fan can be calculated using equation 2, below. Pressure will be estimated using local weather data, fan efficiency will be assumed to be 60%, and air volume is measured.

#### Equation 2, Power Used by Fan
**Zotero source**
P = dp*q/mu

where:

mu = fan efficiency (values between 0 - 1)\
dp = total pressure (Pa) \
q = air volume delivered by the fan (m3/s)\
P = power used by the fan (W, Nm/s)

## Validation of Estimated Energy Consumption
**develop statistically sound estimation procedure outside of inspection?**
Historical data is available for building-wide energy consumption, divided into:

- Chilled water (cooling)
- Steam (heating)
- Electricity

As HVAC operation represents a significant part of building energy consumption, we would expect that trends in and changes of HVAC system energy consumption would closely track with building wide energy consumption. Calculated historical energy consumption is plotted next to building-wide energy consumption for inspection:

**insert plot here**

## Forecasting



# Formal model of data-generating process - PRELIMINARY
What kind of process is it? AR(p)? White noise with drift? Something else?
Write down an equation expressing each realization of the stochastic process yt as a function of other observed data (which could include lagged values of y), unobserved parameters (β), and an error term (εt). Ex:
y=X⋅β+ε
Add a model of the error process. Ex: ε N(0,σ2IT).
If applicable: describe any transformations of the data (e.g., differencing, taking logs) you need to make to get the data into a form (e.g., linear) ready for numerical analysis.

# Discussion of the statistical model
Describe how the formal statistical model captures and aligns with the narrative of the data-generating process.
Flag any statistical challenges raised by the data generating process, e.g.
selection bias; survivorship bias
omitted variables bias
etc.


# References





# Links to sources
- US DOE Report: https://www.energy.gov/sites/prod/files/2017/12/f46/bto-DOE-Comm-HVAC-Report-12-21-17.pdf 
- BTU formulae: 
  - https://www.advantageengineering.com/fyi/288/pdf/advantageIndustrialFormulas.pdf
  - https://www.engineeringtoolbox.com/cooling-heating-equations-d_747.html
  - https://www.energyvanguard.com/blog/converting-heating-and-cooling-loads-air-flow-physics
- Supply Air Temperature: https://www.sciencedirect.com/topics/engineering/supply-air-temperature
- General readings:
  - https://onlinelibrary.wiley.com/doi/full/10.1111/ina.12496?casa_token=WXZVCDnNN9AAAAAA%3A-yxXhqtRRzBjY5bNRnOfwfIpDrbxLWxvaFWFe9TMt17Pbim5uxgKQn4R8EqDvDDaE3mU4svSIxvo9GP2
  - https://www.sciencedirect.com/science/article/pii/S1474667016440887
  - https://www.sciencedirect.com/science/article/pii/S1364032113004322?casa_token=UDbPZbtcuZwAAAAA:aR-hPKZ_P-eEZdsk3nO_pjKVmUum4RKqjDi43Jp4-mTD9MqAc5BhJFo7XG4b2qwNo0FLwpfvmWE
  - https://www.eia.gov/energyexplained/us-energy-facts/



