---
title: "EDA"
author: "Caleb Neale"
date: "3/24/2021"
output: pdf_document
---
# Dataframes from data_cleaning.Rmd
```{r}
library(lubridate)
library(ggplot2)
library(feasts)
library(plotly)

equipment_ops_irreg_ts = as_tsibble(equipment_ops_irreg_ts, key=equipment, index = time)
usa_stacked
ieq_tbl = as_tsibble(ieq_tbl, key= room, index=time)

```
# Summary stats
```{r}
summary(equipment_ops_irreg_ts)
summary(usa_stacked)
summary(ieq_tbl)
```
No eq operation information after January 11, 2021 for some reason

# Summary viz
```{r}
boxplot(usa_stacked %>% as.data.frame() %>% select(air_supply, setpoint))
hist(usa_stacked$air_supply)
hist(usa_stacked$setpoint)
boxplot(ieq_tbl %>% select(co2_ppm_mean, temperature_C, supply_air_flow_cfs, supply_air_flow_setpoint_cfs))
hist(ieq_tbl$temperature_C)
hist(ieq_tbl$co2_ppm_mean)

```
# Plotting the timeseries
```{r}
ggplotly(autoplot(usa_stacked, air_supply))
ggplotly(autoplot(usa_stacked, setpoint))
ggplotly(autoplot(ieq_tbl, co2_ppm_mean))
ggplotly(autoplot(ieq_tbl, temperature_C))
ggplotly(autoplot(ieq_tbl, supply_air_flow_cfs))
ggplotly(autoplot(equipment_ops_irreg_ts, occupied))
```

